### ISSUE TITLE
97: Interior doors sticking

### ISSUE THREAD

**Issue by petertitcomb** [FUYarmouth/Issue-Tracker#12]
Doors sticking:
 1) Door at top of Kitty Corner
 2) Both doors to the Common Room

**Comment by btupper** [comment]
Is this a matter of shaving then down? Or is gravity making them sag?

**Comment by petertitcomb** [comment]
1. Kitty door - I think I'll try shaving. I hope the door frame/building isn't shifting...
2. Common Room doors - Ivory soap fixed worked so far. This area is on a slab, so shouldn't be shifting...
Moisture certainly effects exterior doors.

**Comment by petertitcomb** [comment]
Kitty Door shaved. This seems to have fixed that problem as well.
