### ISSUE TITLE
97 Loose outdoor railing (left-hand side).

### ISSUE THREAD

**Issue by petertitcomb** [FUYarmouth/Issue-Tracker#18]
Left hand outdoor railing at Sanctuary entry is wobbly. The original installation was faulty - one of the 1/4" lag bolts was broken off (total of 4 at each mounting point), others bolts were loose. All bolts now look rusty.
On 6/11/24, I tried to remove one of the loose bolts and that broke off as well!
Possible solutions:
1) Try a bolt extractor bit to remove broken bolts (the steps are a very hard wood).
2) Remount railing a short distance to left/right using drilled pilot holes and stainless hardware.
3) Replace the step boards under the railing mount points and then remount railing(s).

(also, there is a loose step on the lower left of the stairway that is not fixable with just another screw...)

**Comment by btupper** [comment]
Should this one be bumped up to very soon?

**Comment by btupper** [comment]
I pulled the handrail off (breaking all but 2 lag screws).  We can move it 1" to the west and reset.  At each base, the two holes closer to church can use 1/4 x 3" stainless bolts while the two holes closest to the street need to be lagged with 1/4" stainless. We should use tough-gel or similar to separate the stainless from the wrought iron.

**Comment by btupper** [comment]
John A and Ben T reattached with 5/16" stainless bolts.
