### ISSUE TITLE
97 Driveway Nightlight Needs Replacement

### ISSUE THREAD

**Issue by petertitcomb** [FUYarmouth/Issue-Tracker#24]
2024-10-03 The driveway nightlight nearest Main Street is out.
The light is a RAB Lighting WPLED10 (it is rated at 100,000 hours life based on some tests and calculations).
I will order a replacement.

**Comment by petertitcomb** [comment]
Light fixer received and installed. Done!

**Comment by btupper** [comment]
Oh, well done!
