### ISSUE TITLE
97: air leak in sprinkler system

### ISSUE THREAD

**Issue by btupper** [FUYarmouth/Issue-Tracker#5]
Generator running as often as 4h.  Charles has the set-up to monitor again as needed. 

Need to do some spray-bottle investigation.

Issues: long-term wear on compressor, if it can't keep up and pressure drops the sprinkler will trigger unexpectedly.

**Comment by petertitcomb** [comment]
Oops. This is a 97: issue

**Comment by petertitcomb** [comment]
The air leak seems to have increased. I was able to detect the air loss by watching the pressure gauge decline (slowly so far...) and by noticing the compressor seemed to be running more frequently.

An official "quarterly" inspection by Johnson Controls has been scheduled for Dec. 19.

**Comment by petertitcomb** [comment]
Oops. Definitely not "Closed" yet...

**Comment by petertitcomb** [comment]
Compressor pumps up in about 9 minutes.
Air leaks out in about 30 minutes.
So compressor needs to start up every 39 minutes.
(When Charles measured it in early August it was running every 4 hours)

**Comment by btupper** [comment]
![7D920A65-1909-4FC0-A8BE-874BC9FF55E2_1_105_c](https://github.com/FUYarmouth/Issue-Tracker/assets/5097791/a64b5775-e5d1-4a1c-a41a-94366cb5d535)

**Comment by btupper** [comment]
Post-repair monitoring report from Charles...

>I have logged 5 compressor "events" since setting up monitoring yesterday afternoon. Meaning I have 4 intervals recorded. 
>
>Unfortunately, it appears that the intervals between events have shrunk. In August, the intervals were around 4 hours (4:00). Now they appear to be around 3 hours and 37 minutes (3:37). 
>
>Also, the compressor appears to be running longer each time it turns on--about 25 or so seconds longer than in August.

**Comment by btupper** [comment]
Another leak found 2024-02-03 about 8' beyond the most recent fix.  Temporary patch with flex-tape and pipe clamps.

**Comment by btupper** [comment]
Resolved for now with a repair.  We repaired the temporary patch using Pete's super tape, leather backing and many hose clamps.  The backing to support the tape between clamps is key.
